### ISSUE TITLE
Where to listen the session of Branch SDK?

### ISSUE THREAD

**Issue by yashwp** [JaimilPatel/FlutterDeepLink#2]
Do I need to add `FlutterBranchSdk.initSession().listen()` on each screen/stateful widget and listen for changes? Can't I place this under `main.dart` file once for all and navigate user based on data I received in `data` argument?

**Comment by JaimilPatel** [comment]
Not required to add `FlutterBranchSdk.initSession().listen()` on each screen/stateful widget and listen for changes.
